# Generated by Django 5.2.1 on 2025-05-31 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='photos',
        ),
        migrations.CreateModel(
            name='SalonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salon_photos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='salons.salon')),
            ],
            options={
                'verbose_name': 'Фото салона',
                'verbose_name_plural': 'Фотографии салона',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
