# Generated by Django 5.2.1 on 2025-05-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_remove_salon_photos_salonphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='working_hours',
        ),
    ]
