# Generated by Django 5.2.1 on 2025-05-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_remove_salon_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='working_shifts',
        ),
    ]
